name: DevOps Test Pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      # =========================
      # BUILD DA IMAGEM
      # =========================
      - name: Build da imagem Docker
        run: docker build -t devops-test .

      # =========================
      # TESTE DA APLICAÇÃO
      # =========================
      - name: Subir container para teste
        run: docker run -d -p 8080:8080 --name devops-test-container devops-test

      - name: Teste simples da aplicação
        run: |
          echo "Aguardando aplicação subir..."
          sleep 5

          echo "Chamando aplicação:"
          curl http://localhost:8080

          echo ""
          echo "Logs do container:"
          docker logs devops-test-container

      - name: Remover container de teste
        run: docker rm -f devops-test-container

      # =========================
      # TERRAFORM
      # =========================
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        working-directory: terraform
        run: terraform init

      - name: Terraform Apply
        working-directory: terraform
        run: terraform apply -auto-approve

      - name: Validar aplicação provisionada pelo Terraform
        run: |
          echo "Aguardando aplicação provisionada subir..."
          sleep 5
          echo "Resposta da aplicação após Terraform:"
          curl http://localhost:8080
