name: DevOps Test Pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Build da imagem Docker
        run: docker build -t devops-test .

      - name: Subir container para teste
        run: |
          docker run -d -p 8080:8080 --name devops-test-container devops-test
          sleep 5

      - name: Teste simples da aplicação
        run: |
          echo "Acessando aplicação..."
          
          for i in {1..10}; do
            RESPONSE=$(curl -s http://localhost:8080)
      
            if [ ! -z "$RESPONSE" ]; then
              echo "Resposta da aplicação:"
              echo "$RESPONSE"
              exit 0
            fi
      
            echo "Aguardando aplicação subir..."
            sleep 2
          done
      
          echo "Falha ao acessar aplicação"
          docker logs devops-test-container
          exit 1

      - name: Remover container de teste
        run: docker rm -f devops-test-container

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        working-directory: terraform
        run: terraform init

      - name: Terraform Apply
        working-directory: terraform
        run: terraform apply -auto-approve
